In [4]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [5]:
import cv2
import numpy as np

In [6]:
# Load an image using 'imread' specifying the path to image
image = cv2.imread('C:/Users/91630/Downloads/husky.jpg',0)

# Our file 'input.jpg' is now loaded and stored in python 
# as a varaible we named 'image'

# To display our image variable, we use 'imshow'
# The first parameter will be title shown on image window
# The second parameter is the image varialbe
cv2.imshow("test image", image)

# 'waitKey' allows us to input information when a image window is open
# By leaving it blank it just waits for anykey to be pressed before 
# By placing numbers (except 0), we can specify a delay for how long you keep the window open (time is in milliseconds here)
cv2.waitKey()

# This closes all open windows 
# Failure to place this will cause your program to hang
cv2.destroyAllWindows()


# Let's take a closer look at how images are stored

In [41]:
## Images are stored as numpy arrays

print(image) 

[[[198 139  53]
  [199 140  54]
  [198 141  56]
  ...
  [212 132   1]
  [211 131   0]
  [211 131   0]]

 [[198 139  53]
  [199 140  54]
  [198 141  56]
  ...
  [212 132   1]
  [211 131   0]
  [210 130   0]]

 [[198 140  51]
  [199 141  52]
  [200 141  55]
  ...
  [209 131   0]
  [208 130   0]
  [208 130   0]]

 ...

 [[ 46 125 176]
  [ 61 140 191]
  [ 70 149 200]
  ...
  [ 20  36  65]
  [ 25  42  75]
  [ 59  76 109]]

 [[ 49 134 184]
  [ 48 133 183]
  [ 47 130 181]
  ...
  [  0   3  33]
  [  1  10  44]
  [ 41  50  84]]

 [[ 56 145 195]
  [ 58 147 197]
  [ 64 149 199]
  ...
  [ 64  69 100]
  [ 30  34  69]
  [  0   3  38]]]


# Shape gives the dimensions of the image array

In [42]:
image.shape   ## (height, width, channels)  ## for colourful images with RGB the channels will be 3

(800, 1200, 3)

In [4]:
print(image.shape)

(500, 231, 3)


# Basic image processing Operations

In [43]:
## Resizing the image

import cv2

# Load the image
image1 = cv2.imread('C:/Users/91630/Downloads/husky.jpg', 1)

# Resize the image, set the desired new image size
resized = cv2.resize(image1, (600, 500))

# Convert the resized image to grayscale
gray = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)

# Display the original and resized images
cv2.imshow("Original Image", image1)
cv2.imshow("Resized Image", resized)
cv2.imshow("Grayscale Image", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()


### Image filtering: OpenCV provides various functions for applying filters to images, such as Gaussian blur, median blur, and bilateral filter, using functions like cv2.GaussianBlur(), cv2.medianBlur(), and cv2.bilateralFilter(), respectively.

In [44]:
##Gaussian Blur

import cv2

# Load the image
image4 = cv2.imread('C:/Users/91630/Downloads/img1.jpg',1)


# Display the original image
cv2.imshow('Original Image', image4)

# Apply Gaussian blur filtering
ksize = (9, 9)  # Kernel size (odd number)
sigmaX = 0      # Standard deviation along X-axis (0 means calculated based on ksize)
sigmaY = 0      # Standard deviation along Y-axis (0 means calculated based on ksize)
blurred_image = cv2.GaussianBlur(image4, ksize, sigmaX, sigmaY)

# Display the blurred image
cv2.imshow('Blurred Image', blurred_image)

# Wait for a key press and then close all open windows
cv2.waitKey(0)
cv2.destroyAllWindows()


In [19]:
##thresholding

import cv2

# Load the image
image5 = cv2.imread('C:/Users/91630/Downloads/img1.jpg', cv2.IMREAD_GRAYSCALE)


# Display the original image
cv2.imshow('Original Image', image5)

# Apply thresholding
ret, thresh_image = cv2.threshold(image5, 127, 255, cv2.THRESH_BINARY)

# Display the thresholded image
cv2.imshow('Thresholded Image', thresh_image)

# Wait for a key press and then close all open windows
cv2.waitKey(0)
cv2.destroyAllWindows()


### Image drawing: OpenCV provides functions for drawing various shapes, lines, and texts on images. Functions like cv2.line(), cv2.rectangle(), cv2.circle(), and cv2.putText() can be used to draw lines, rectangles, circles, and texts, respectively, on images.

# How do we save images in OpenCV?

In [45]:
cv2.imwrite('image.png',image5)     ## We can save images in whichever format we want just by specifying it 
cv2.imwrite('image.jpg',image5)

True

# Face Detection using HAAR Cascade Classifiers

In [1]:
## face detection

import cv2
import numpy as np
# We point OpenCV's CascadeClassifier function to where our 
# classifier (XML file format) is stored
face_classifier = cv2.CascadeClassifier('C:/Users/91630/OneDrive/Documents/FP/haarcascade_frontalface_default.xml')

# Load our image then convert it to grayscale
image = cv2.imread('C:/Users/91630/OneDrive/Documents/FP/Trumph.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Our classifier returns the ROI of the detected face as a tuple
# It stores the top left coordinate and the bottom right coordiantes
faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No faces found")

# We iterate through our faces array and draw a rectangle
# over each face in faces
for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (100,0,200), 2)
    #cv2.circle(image, (100, 200), 50, (127, 0, 255), 2)
    cv2.imshow('Face Detection', image)
    #cv2.imshow("Image with Circle", image)
    cv2.waitKey(0)
    
    
cv2.destroyAllWindows()

<>:18: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:18: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\91630\AppData\Local\Temp\ipykernel_8816\3029917752.py:18: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# Car & Pedestrian Detection

In [25]:
## Car detection

import cv2
import time
import numpy as np

# Create our body classifier
car_classifier = cv2.CascadeClassifier('C:/Users/91630/OneDrive/Documents/FP/haarcascade_car.xml')

# Initiate video capture for video file
cap = cv2.VideoCapture('C:/Users/91630/OneDrive/Documents/FP/car.MP4')


# Loop once video is successfully loaded
while cap.isOpened():
    
    time.sleep(.05)
    # Read first frame
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
   
    # Pass frame to our car classifier
    cars = car_classifier.detectMultiScale(gray, 1.4, 2)
    
    # Extract bounding boxes for any bodies identified
    for (x,y,w,h) in cars:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 255), 2)
        cv2.imshow('Cars', frame)

    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()

In [9]:
##Fullbody recognition (pedestrian recognition)

import cv2
import numpy as np

# Create our body classifier
body_classifier = cv2.CascadeClassifier('C:/Users/91630/OneDrive/Documents/FP/haarcascade_fullbody.xml')

# Initiate video capture for video file
cap = cv2.VideoCapture('C:/Users/91630/OneDrive/Documents/FP/pedestrian.MP4')

# Loop once video is successfully loaded
while cap.isOpened():
    
    # Read first frame
    ret, frame = cap.read()
    #frame = cv2.resize(frame, None,fx=0.5, fy=0.5, interpolation = cv2.INTER_LINEAR)

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # Pass frame to our body classifier
    bodies = body_classifier.detectMultiScale(gray, 1.2, 3)
    
    # Extract bounding boxes for any bodies identified
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 255), 2)
        cv2.imshow('Pedestrians', frame)

    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()

# Let's make a live face & eye detection, keeping the face inview at all times

In [8]:
import cv2

# Loading the cascades
face_cascade = cv2.CascadeClassifier('C:/Users/91630/OneDrive/Documents/FP/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('C:/Users/91630/OneDrive/Documents/FP/haarcascade_eye.xml')

# Defining a function that will do the detections
def detect(gray, frame):
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.1, 3)
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (0, 255, 0), 2)
    return frame

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas = detect(gray, frame)
    cv2.imshow('Video', canvas)
    if cv2.waitKey(1) & 0xFF == ord('k'):
        break
video_capture.release()
cv2.destroyAllWindows()

## THE END